apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nginx.name }}-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.nginx.name }}
spec:
  selector:
    app: {{ .Values.nginx.name }}
  ports:
  - port: {{ .Values.nginx.containerPort }}
    targetPort: {{ .Values.nginx.containerPort }}
